name: Deploy

on:
  push:
    branches:
      - "main"

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6' 
      - run: pip install -r requirements.txt
      - run: pytest